CC=gcc
TARGET=$(PWD)/result.o
CFLAGS  = -g -Wall

#all:ll.o ll_adt.o ll_problem.o
all:
	echo "creating Binary search Tree exec"
	$(CC) $(CFLAGS) *.c -o $(TARGET)

clean:
	echo "cleaning Binary search Tree exec"
		rm *.o $(TARGET)