#%.o: %.cpp %.hpp
CC = g++
#CFLAGS=
CFLAGS = -g -Wall

09_stl_pq.o: 09_stl_pq.cpp
			$(CC) $(CFLAGS)  -o 09_stl_pq.o 09_stl_pq.cpp

08_stl_map.o: 08_stl_map.cpp
			$(CC) $(CFLAGS)  -o 08_stl_map.o 08_stl_map.cpp

07_stl_deque.o: 07_stl_deque.cpp
			$(CC) $(CFLAGS)  -o 07_stl_deque.o 07_stl_deque.cpp

06_stl_vector.o: 06_stl_vector.cpp
			$(CC) $(CFLAGS)  -o 06_stl_vector.o 06_stl_vector.cpp

05_stl_algos.o: 05_stl_algos.cpp
			$(CC) $(CFLAGS)  -o 05_stl_algos.o 05_stl_algos.cpp

04_iterators.o: 04_iterators.cpp
			$(CC) $(CFLAGS)  -o 04_iterators.o 04_iterators.cpp

03_class_template.o: 03_class_template.cpp
			$(CC) $(CFLAGS)  -o 03_class_template.o 03_class_template.cpp
02_function_template.o: 02_function_template.cpp
			$(CC) $(CFLAGS)  -o 02_function_template.o 02_function_template.cpp
			
01_stl_ex.o: 01_stl_ex.cpp
			$(CC) $(CFLAGS)  -o 01_stl_ex.o 01_stl_ex.cpp


clean:
	$(RM) *.o*